spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Mohamed Emad - Developer"
    email: "mohamed.emad.hashad@gmail.com"
  onCallSupport:
    - +201062202253
