server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cards
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: CARD-SERVICE

