spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Mohamed Emad - Developer"
    email: "mohamed.emad.hashad@gmail.com"
  onCallSupport:
    - +201062202253
