build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Mohamed Emad - Developer"
    email: "mohamed.emad.hashad@gmail.com"
  onCallSupport:
    - +201062202253
